config/routes.rb
Rails.application.routes.draw do
mount SolidusPaypalCommercePlatform::Engine, at: '/solidus_paypal_commerce_platform'
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  authenticated :spree_user, ->(u) { u&.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Spree::Core::Engine, at: '/'
  get '/export', to: 'spree/admin/products#export'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/export_interested_chapters', to: 'spree/admin/interested_chapters#export'
  get '/export_ffa_chapter_enrollments', to: 'spree/admin/ffa_chapter_enrollments#export'
  get '/export_ffa_fundraiser', to: 'spree/admin/ffa_fundraiser_calculations#export'
  post '/ebay_webhook', to: 'ebay_webhook#get_data'
  #get '/ebay_token', to: 'ebay_webhook#token_callback'

  resource :news_letter, only: [:create], defaults: { format: 'js' }

  Spree::Core::Engine.routes.draw do
    resources :stock_updates, only: [:new, :create]
    devise_scope :spree_user do
      post 'user_registration', to: 'user_sessions#user_registration'
      post 'forget_password', to: 'user_sessions#forget_password'
    end

    devise_for :spree_user,class_name: Spree.user_class, only: [:omniauth_callbacks], controllers: { omniauth_callbacks: 'spree/user_omniauth_callbacks' }

    namespace :admin do
      resources :product_questions, only: [:index, :destroy, :edit, :update] do
        member do
          get :publish
        end
      end
      resources :cta_images
      resources :contacts, only: [:index, :show]
      resources :labels
      resources :featured_products, only: [:index] do
        collection do
          post :update_positions
        end
      end

      resources :deals_products, only: [:index] do
        collection do
          post :update_deals_position
        end
      end
      resources :google_product_categories, only: [:index, :create]
      resources :bulk_update_product_prices, only: [:index, :create]
      resources :bulk_update_sale_prices, only: [:index, :create]
      resources :email_logs, only: [:index]
      resources :ffa_chapter_enrollments
      resources :change_logs, only: [:index]
      resources :ebay_change_logs, only: [:index]
      resources :ns_responses, only: [:index]
      resources :ffa_fundraiser_events, only: [:index, :create, :update]
      resources :help_centers do
        collection do
          post :update_positions
        end
      end
      resources :bulk_update_product_labels, only: [:index, :create]

      resources :tracking_lookups

      resources :labels_products, only: [:index] do
        collection do
          post :update_positions
        end
      end

      resources :store_credit_winners

      resources :ffa_fundraiser_calculations, only: [:index, :show]

      resources :facebook_api_logs, only: [:index] do
        collection do
          post :update_product_catalog
        end
      end

      resources :filter_types do
        collection do
          post :update_positions
          post :update_values_positions
        end
      end

      get '/products/:id/group_products', to: "products#group_products" , as: :group_products
      post '/products/:id/group_products', to: "products#add_group_products" , as: :add_group_products
      delete '/products/:id/group_products', to: "products#remove_group_product" , as: :remove_group_product
      post '/products/:id/add_on_product', to: "products#add_add_on_product" , as: :add_add_on_products
      get '/products/:id/add_on_product', to: "products#add_on_product" , as: :add_on_products
      delete '/products/:id/add_on_product', to: "products#remove_add_on_product" , as: :remove_add_on_product


      resources :home_page_reviews do
        collection do
          post :update_positions
        end
      end

      resources :cta_images do
        collection do
          post :update_positions
        end
      end

      delete '/filter_values/:id', to: "filter_values#destroy", as: :filter_value
      delete '/deals_page/:id/remove_image', to: "deals_page#remove_image" , as: :remove_image
      put '/deals_page/:id/edit_image', to: "deals_page#edit_image" , as: :edit_image
      get '/export_users_data', to: 'users#export'

      resources :deals_page
      resources :ebay_logs, only: [:index]
      resources :net_suite_logs, only: [:index]
      resources :net_suite_auth, only: [:index] do
        collection do
          get :consent_approved
        end
      end

      resources :interested_chapters, only: [:index, :edit, :update, :destroy]

      resources :products do
        member do
          get :bulk_update_variant_prices
        end
      end
    end

    resources :products do
      collection do
        get :deals
        get :gift_page
        get :product_reviews
        get :stock_update_notification
      end

      member do
        get :show_related
        get :reviews_form
        get :question_form
      end
    end

    resources :save_items, only: [:index, :create, :destroy]

    resources :product_categories, only: [:index, :show]
    resources :contacts, only: [:create, :new]
    resources :store_credit_winners, only: [:create, :new]

    resources :products, only: [] do
      resources :product_questions, only: %i[create new index update]
    end

    get '/product/id', to: 'products#quick_view', as: :quick_view
    get '/taxon_with_children', to: 'taxons#load_taxon_children', as: :load_taxon_children
    get '/update_upsell_modal', to: 'orders#update_upsell_modal'
    resources :taxon_options, only: [:index], defaults: { format: 'js' }
    resources :custom_hose_generator, only: [:index]
    delete '/cart/destroy_line_item', to: 'orders#destroy_line_item'
    get '/cart/increase_quantity', to: 'orders#increase_quantity'
    get '/cart/decrease_quantity', to: 'orders#decrease_quantity'
    get '/cart/update_line_item_quantity', to: 'orders#update_line_item_quantity'
    get '/', to: 'home#index_v2'
    get 'featured_products_cards', to: 'home#featured_products_cards'
    get 'best_seller_products_cards', to: 'home#best_seller_products_cards'
    get 'site_wide_products_cards', to: 'home#site_wide_products_cards'
    get 'recently_viewed_products_cards', to: 'home#recently_viewed_products_cards'
    get 'ffa_products_cards', to: 'ffa_home#ffa_products_cards'

    get '/faqs', to: 'pages#faq'
    get '/faqs_page', to: 'pages#faq_page'
    get '/privacy_policy', to: 'pages#privacy_policy'
    get '/mill', to: 'pages#mill'
    get '/shipping_policy', to: 'pages#shipping_policy'
    get '/about_us', to: 'pages#about_us'
    get '/freedom_wrap', to: 'pages#freedom_wrap'
    delete '/custom_hose_configuration', to: 'orders#destroy_custom_hose_from_line_items'
    delete '/remove_coupon', to: 'coupon_codes#remove_coupon'
    resources :ffa_fundraisers, path: :enroll
    patch 'update_chapter', to: 'checkout#update_chapter'
    post 'apply_shipment', to: 'checkout#apply_shipment_total'
    post 'remove_payment_source', to: 'checkout#remove_card_from_wallet'
    get '/august_event', to: 'pages#august_event'
    get '/populate_qty_modal', to: 'checkout#populate_qty_modal'
    get '/chuckwagon_dvd', to: 'pages#chuckwagon_dvd'
    get '/net_wraps', to: 'pages#net_wraps'
    get '/usa', to: 'pages#usa'
    get 'briddon_usa_flag_products_cards', to: 'pages#briddon_usa_flag_products_cards'
    get 'ariat_flag_products_cards', to: 'pages#ariat_flag_products_cards'
    get 'allied_flag_products_cards', to: 'pages#allied_flag_products_cards'
    get 'accessories_flag_products_cards', to: 'pages#accessories_flag_products_cards'
    get 'related_products_cards', to: 'products#related_products_cards'

    resources :e_signatures, only: [:new] do
      collection do
        post 'callbacks'
        get 'signature_url'
      end
    end

    resources :ffa_home, path: :ffa, only: [:index]
    resources :interested_chapters, only: [:create]
    resource :ns_products_data_sync, only: [:create]
    resource :paypal_tracking_number_sync, only: [:create]

    get '.well-known/apple-developer-merchantid-domain-association', to: 'stripe_apple_pay_verification_file#show'
  end
end

# touched on 2025-07-09T20:39:47.427166Z
# touched on 2025-07-09T21:00:56.925481Z
# touched on 2025-07-09T21:01:40.042415Z
# touched on 2025-07-09T21:22:03.104733Z

app/models/spree/order/payments.rb
# frozen_string_literal: true

module Spree
  class Order < Spree::Base
    module Payments
      # processes any pending payments and must return a boolean as it's
      # return value is used by the checkout state_machine to determine
      # success or failure of the 'complete' event for the order
      #
      # Returns:
      #
      # - true if all pending payments processed successfully
      #
      # - true if a payment failed, ie. raised a GatewayError
      #   which gets rescued and converted to TRUE when
      #   :allow_checkout_gateway_error is set to true
      #
      # - false if a payment failed, ie. raised a GatewayError
      #   which gets rescued and converted to FALSE when
      #   :allow_checkout_on_gateway_error is set to false
      #
      def process_payments!
        process_payments_with(:process!)
      end

      def authorize_payments!
        process_payments_with(:authorize!)
      end

      def capture_payments!
        process_payments_with(:purchase!)
      end

      def unprocessed_payments
        payments.select(&:checkout?)
      end

      private

      def process_payments_with(method_name)
        # Don't run if there is nothing to pay.
        return true if payment_total >= total

        unprocessed_payments.each do |payment|
          break if payment_total >= total

          payment.public_send(method_name)
        end
      rescue Core::GatewayError => error
        result = !!Spree::Config[:allow_checkout_on_gateway_error]
        errors.add(:base, error.message) && (return result)
      end
    end
  end
end

# touched on 2025-07-09T19:40:13.462055Z
# touched on 2025-07-09T20:54:09.059537Z

app/controllers/solidus_paypal_commerce_platform/orders_controller.rb
# frozen_string_literal: true

module SolidusPaypalCommercePlatform
  class OrdersController < ::Spree::Api::BaseController
    skip_before_action :authenticate_user
    include ::Spree::Core::ControllerHelpers::Auth

    def create
      authorize! :create, ::Spree::Order

      @order = ::Spree::Order.create!(
        user: current_api_user,
        store: current_store,
        currency: current_pricing_options.currency
      )

      if @order.contents.update_cart order_params
        # Overriding any existing orders
        cookies.signed[:guest_token] = @order.guest_token
        render json: @order, status: :ok
      else
        render json: @order.errors.full_messages, status: :unprocessable_entity
      end
    end

    def update_address
      load_order
      authorize! :update, @order, order_token
      paypal_address = SolidusPaypalCommercePlatform::PaypalAddress.new(@order)

      if paypal_address.update(paypal_address_params).valid?
        #@order.ensure_updated_shipments

        @order.contents.advance
        render json: {}, status: :ok
      else
        render json: paypal_address.errors.full_messages, status: :unprocessable_entity
      end
    end

    def verify_total
      load_order
      authorize! :show, @order, order_token

      if total_is_correct?(params[:paypal_total])
        render json: {}, status: :ok
      else
        respond_with(@order, default_template: 'spree/api/orders/expected_total_mismatch', status: 400)
      end
    end

    private

    def total_is_correct?(paypal_total)
      @order.total == BigDecimal(paypal_total)
    end

    def paypal_address_params
      params.require(:address).permit(
        updated_address: [
          :address_line_1,
          :address_line_2,
          :admin_area_1,
          :admin_area_2,
          :postal_code,
          :country_code,
        ],
        recipient: [
          :email_address,
          {
            name: [
              :given_name,
              :surname,
            ]
          }
        ]
      )
    end

    def order_params
      params.require(:order).permit(permitted_order_attributes)
    end

    def load_order
      @order = ::Spree::Order.find_by!(number: params[:order_id])
    end
  end
end

# touched on 2025-07-09T17:43:09.054511Z

app/views/spree/admin/orders/_carton.html.erb
<div id="<%= dom_id(carton) %>" data-hook="admin_carton_form">
  <fieldset class="no-border-bottom">
    <legend align="center" class="stock-location" data-hook="stock-location">
      <span class="carton-number"><%= carton.number %></span>
      -
      <span class="carton-state"><%= t('spree.shipment_states.shipped') %></span>
      <span class="carton-exchange"><%= Spree::Exchange.model_name.human if carton.any_exchanges? %></span>
      <%= t('spree.package_from') %>
      <strong class="stock-location-name" data-hook="stock-location-name">'<%= carton.stock_location.name %>'</strong>
    </legend>
  </fieldset>

  <table class="stock-contents carton index" data-hook="stock-contents">
    <colgroup>
      <col style="width: 10%;" />
      <col style="width: 45%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
    </colgroup>

    <thead>
      <th colspan="2"><%= Spree::LineItem.human_attribute_name(:description) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:price) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:quantity) %></th>
      <th><%= Spree::LineItem.human_attribute_name(:total) %></th>
    </thead>

    <tbody data-hook="carton-details" data-shipment-number="<%= carton.number %>" data-order-number="<%= order.number %>">
      <%= render 'spree/admin/orders/carton_manifest', carton: carton, order: order %>

      <tr class="show-method total">
        <% if method = carton.shipping_method %>
          <td colspan="5">
            <strong><%= method.name %></strong>
          </td>
        <% else %>
          <td colspan='5'><%= t('spree.no_shipping_method_selected') %></td>
        <% end %>
      </tr>

      <% if order.special_instructions.present? %>
        <tr class='special_instructions'>
          <td colspan="5">
            <strong><%= Spree::Order.human_attribute_name(:special_instructions) %>:&nbsp;</strong><%= order.special_instructions %>
          </td>
        </tr>
      <% end %>

      <tr class="show-tracking total">
        <td colspan="5">
          <% if carton.tracking.present? %>
            <strong><%= Spree::Carton.human_attribute_name(:tracking) %>:</strong>
            <% if carton.tracking_url %>
              <%= link_to carton.tracking, carton.tracking_url, target: "_blank" %>
            <% else %>
              <%= carton.tracking %>
            <% end %>
          <% else %>
            <i><%= t('spree.no_tracking_present') %></i>
          <% end %>
        </td>
      </tr>

      <tr class='shipment-numbers'>
        <td colspan="5">
          <strong><%= t('spree.shipment_numbers') %>:&nbsp;</strong><%= carton.shipment_numbers.join(", ") %>
        </td>
      </tr>

      <tr class='ship-date'>
        <td colspan="5">
          <% if params['time_zone'] == 'CST' %>
            <strong><%= t('spree.shipment_date') %>:&nbsp;</strong><%= carton.display_shipped_at.in_time_zone("Central Time (US & Canada)").strftime("%Y-%m-%d %H:%M:%S %Z") %>
          <% else %>
            <strong><%= t('spree.shipment_date') %>:&nbsp;</strong><%= carton.display_shipped_at.in_time_zone("UTC").strftime("%Y-%m-%d %H:%M:%S %Z") %>
          <% end %>
        </td>
      </tr>

      <% if carton.orders.size > 1 %>
        <tr class='order-numbers'>
          <td colspan="5">
            <strong><%= t('spree.carton_orders') %>:&nbsp;</strong>
            <% (carton.orders - [order]).each do |order| %>
              <%= link_to order.number, edit_admin_order_path(order) %>
            <% end %>
          </td>
        </tr>
      <% end %>

      <% if carton.external_number.present? %>
        <tr class="external-number">
          <td colspan="5">
            <strong><%= t('spree.carton_external_number') %>:&nbsp;</strong><%= carton.external_number %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

# touched on 2025-07-09T17:38:35.822265Z
# touched on 2025-07-09T18:18:04.333178Z
# touched on 2025-07-09T20:38:46.450980Z
# touched on 2025-07-09T20:59:36.986996Z
# touched on 2025-07-09T21:24:05.547685Z

app/views/spree/admin/orders/_form.html.erb
 <div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
    <%= render partial: 'spree/shared/error_messages', locals: { target: @line_item } %>
  <% end %>

  <%= render :partial => "spree/admin/orders/carton", collection: @order.cartons.order(:shipped_at), locals: { order: order } %>
  <%= render :partial => "spree/admin/orders/shipment", collection: @order.shipments.order(:created_at), locals: { order: order } %>

  <%= render "spree/admin/orders/order_details", { order: order } %>

  <%= javascript_tag do -%>
    var order_number = '<%= @order.number %>';
    var shipments = [];
    <% @order.shipments.each do |shipment| %>
            shipments.push(<%== shipment.as_json(root: false, only: [:id, :tracking, :tracking_lookup, :number, :state, :stock_location_id], include: [:inventory_units, :stock_location]).to_json %>);
    <% end %>
  <% end -%>
</div>

# touched on 2025-07-09T17:33:31.615337Z
# touched on 2025-07-09T17:37:07.380795Z
# touched on 2025-07-09T20:36:01.388404Z
# touched on 2025-07-09T20:36:08.955537Z

app/views/spree/admin/orders/confirm.html.erb
<%= render partial: 'spree/admin/shared/order_tabs', locals: {current: 'Confirm'} %>

<% admin_breadcrumb(t('spree.confirm_order')) %>


<%= render partial: 'spree/admin/orders/confirm/customer_details', locals: {order: @order} %>

<% if Spree::Order.checkout_step_names.include?(:payment) && @order.shipments.present? %>
  <%= render partial: 'spree/admin/orders/confirm/shipment', collection: @order.shipments, locals: {order: @order} %>
<% else %>
  <%= render partial: 'spree/admin/orders/confirm/line_items', locals: {order: @order} %>
<% end %>

<%=
  render(
    partial: 'spree/admin/orders/adjustments',
    locals: {
      adjustments: @order.line_item_adjustments,
      order: @order,
      title: t('spree.line_item_adjustments'),
    }
  ) if @order.line_item_adjustments.eligible.any?
%>

<%=
  render(
    partial: 'spree/admin/orders/adjustments',
    locals: {
      adjustments: @order.shipment_adjustments,
      order: @order,
      title: t('spree.shipment_adjustments'),
    }
  ) if @order.shipment_adjustments.eligible.any?
%>

<%=
  render(
    partial: 'spree/admin/orders/adjustments',
    locals: {
      adjustments: @order.adjustments,
      order: @order,
      title: t('spree.order_adjustments'),
    }
  ) if @order.adjustments.eligible.any?
%>

<% if @order.line_items.exists? %>
  <fieldset class="no-border-bottom" id="order-total" data-hook="order_details_total">
    <legend><%= t('spree.order_total') %></legend>
    <span class="order-total"><%= @order.display_total %></span>
  </fieldset>
<% end %>

<%= render partial: 'spree/admin/orders/confirm/payments', locals: {payments: @order.payments} %>

<div class="form-buttons filter-actions actions" data-hook="complete-order-button">
  <%= button_to [:complete, :admin, @order], { class: 'button', method: 'put' } do %>
    <%= t('spree.complete_order') %>
  <% end %>
</div>

# touched on 2025-07-09T17:44:28.058914Z
# touched on 2025-07-09T19:38:37.294685Z

app/views/spree/admin/orders/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(plural_resource_name(Spree::Order)) %>


<% content_for :page_actions do %>
  <li>
    <%= link_to t('spree.new_order'), new_admin_order_url, id: 'admin_new_order', class: 'btn btn-primary' %>
  </li>
<% end if can? :manage, Spree::Order %>

<% content_for :table_filter_title do %>
  <%= t('spree.filter') %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="field-block col-12 col-md-6 col-lg-4 col-xl-3">
          <div class="date-range-filter field">
            <%= label_tag :q_created_at_gt, t('spree.date_range') %>
            <div class="date-range-fields input-group">
              <%= f.text_field :created_at_gt, class: 'datepicker form-control datepicker-from', value: params[:q][:created_at_gt], placeholder: t('spree.start') %>

              <div class="input-group-prepend input-group-append">
                <span class="input-group-text range-divider">
                  <i class="fa fa-arrow-right"></i>
                </span>
              </div>

              <%= f.text_field :created_at_lt, class: 'datepicker form-control datepicker-to', value: params[:q][:created_at_lt], placeholder: t('spree.stop') %>
            </div>
          </div>

          <div class="field">
            <%= label_tag :q_state_eq, t('spree.status') %>
            <%= f.select :state_eq, Spree::Order.state_machines[:state].states.collect {|s| [t(s.name, scope: 'spree.order_state'), s.value]}, {include_blank: true}, class: 'custom-select fullwidth' %>
          </div>

          <div class="field">
            <%= label_tag nil, t('spree.promotion') %>
            <%= f.text_field :order_promotions_promotion_code_value_start, size: 25 %>
          </div>

          <div class="field">
            <%= label_tag nil, t('spree.shipment_number') %>
            <%= f.text_field :shipments_number_start %>
          </div>

          <div class="field">
            <%= label_tag :q_shipment_state, t('spree.shipment_state') %>
            <%= f.select :shipment_state_eq, %i[backorder canceled partial pending ready shipped].map { |state| [t("spree.shipment_states.#{state}"), state] }, { include_blank: true }, { class: "custom-select fullwidth" } %>
          </div>

        </div>

        <div class="col-12 col-md-6 col-lg-4 col-xl-6">
          <div class="row">
            <div class="col-12 col-xl-6">
              <div class="field">
                <%= label_tag :q_number_start, t('spree.order_number', number: '') %>
                <%= f.text_field :number_start %>
              </div>

              <div class="field">
                <%= label_tag :q_email_start, t('spree.email') %>
                <%= f.text_field :email_start %>
              </div>
            </div>

            <div class="col-12 col-xl-6">
              <div class="field">
                <%= label_tag :q_bill_address_firstmame_cont, t('spree.name_contains') %>
                <%= f.text_field :bill_address_firstname_cont, size: 25 %>
              </div>


              <div class="field checkbox">
                <label>
                  <%= f.check_box :pick_up, {checked: @show_only_pickup_orders}, '1', '0' %>
                  Show only Pickup orders
                </label>
              </div>
            </div>

            <div class="col-12 col-xl-6">
              <div class="field" data-hook="sku-select">
                <%= label_tag :q_line_items_variant_id_in, t('spree.variant') %>
                <%= f.text_field :line_items_variant_id_in, class: "variant_autocomplete fullwidth" %>
              </div>

              <div class="field">
                <%= label_tag :q_utm_source_start, 'UTM Source' %>
                <%= f.text_field :utm_source_start, class: "fullwidth" %>
              </div>
              <div class="field">
                <%= label_tag :q_ref_start, 'Ref' %>
                <%= f.text_field :ref_start, class: "fullwidth" %>
              </div>
            </div>

            <div class="col-12 col-xl-6">
              <div class="field">
                <%= label_tag :q_tar_start, 'Tar' %>
                <%= f.text_field :tar_start, class: "fullwidth" %>
              </div>
            </div>

          </div>
        </div>

        <div class="col-12 col-md-6 col-lg-4 col-xl-3">
          <% if Spree::Store.count > 1 %>
            <div class="field">
              <%= label_tag :q_store_id_eq, t('spree.store') %>
              <%= f.select :store_id_eq, Spree::Store.all.map { |s| [s.name, s.id] }, { include_blank: true }, { class: "custom-select fullwidth" } %>
            </div>
          <% end %>

          <div class="field checkbox">
            <label>
              <%= f.check_box :completed_at_not_null, {checked: @show_only_completed}, '1', '0' %>
              <%= t('spree.show_only_complete_orders') %>
            </label>
          </div>

          <div class="field checkbox">
            <label>
              <%= f.check_box :hide_pick_up, {checked: @hide_pickup_orders}, '1', '0' %>
              Hide pickup orders
            </label>
          </div>
        </div>

      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div data-hook="admin_orders_index_search_buttons">
          <%= button_tag t('spree.filter_results'), class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<%= paginate @orders, theme: "solidus_admin" %>

<% if @orders.any? %>
  <table class="index" id="listing_orders" data-hook>
    <colgroup>
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <col style="width: 10%;">
       <% if Spree::Order.checkout_step_names.include?(:payment) %>
         <col style="width: 10%;">
       <% end %>
       <col style="width: 12%;">
       <col style="width: 10%;">
       <col style="width: 9%;">
       <col style="width: 9%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at %></th>
        <% else %>
          <th><%= sort_link @search, :created_at %></th>
        <% end %>
        <th><%= sort_link @search, :number %></th>
        <th><%= sort_link @search, :state %></th>
        <th><%= sort_link @search, :payment_state %></th>
        <% if Spree::Order.checkout_step_names.include?(:payment) %>
          <th><%= sort_link @search, :shipment_state %></th>
        <% end %>
        <th><%= sort_link @search, :email %></th>
        <th><%= sort_link @search, :utm_source %></th>
        <th><%= sort_link @search, :tar %></th>
        <th><%= sort_link @search, :ref %></th>

        <th class="align-right"><%= sort_link @search, :total %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <div class='mb-3'>
      <%= form_with controller: 'orders', action: 'index', method: :get do |f| %>
        <%= f.label :time_zone, "Select timezone: " %>
        <%= f.select :time_zone, options_for_select(['CST', 'UTC'], selected: params['time_zone'] || nil), {}, class: 'custom-select w-25' %>
        <%= f.submit "Apply", class: 'btn btn-primary' %>
      <% end %>
    </div>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows">
        <% if params['time_zone'] == 'UTC' %>
          <td><%= (@show_only_completed ? order.completed_at : order.created_at).in_time_zone("UTC").strftime('%d-%m-%Y %Z') %></td>
        <% else %>
          <td><%= (@show_only_completed ? order.completed_at : order.created_at).in_time_zone("Central Time (US & Canada)").strftime('%d-%m-%Y %Z') %></td>
        <% end %>
        <td><%= link_to order.number, edit_admin_order_path(order, time_zone: params['time_zone']) %></td>
        <td>
          <span class="pill pill-<%= order.state %>">
            <%= t(order.state, scope: 'spree.order_state') %>
          </span>
        </td>
        <td>
          <% if order.payment_state  %>
            <span class="pill pill-<%= order.payment_state %>">
              <%= t(order.payment_state, scope: 'spree.payment_states') %>
            </span>
          <% end %>
        </td>
        <% if Spree::Order.checkout_step_names.include?(:payment) %>
          <td>
            <% if order.shipment_state %>
              <span class="pill pill-<%= order.shipment_state %>">
                <%= t(order.shipment_state, scope: 'spree.shipment_states') %>
              </span>
            <% end %>
          </td>
        <% end %>
        <td>
          <% if order.user %>
            <%= link_to order.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= order.email %>
          <% end %>
          <%= link_to_with_icon('email', t('spree.actions.send_email'), "mailto:#{order.email}", no_text: true) %>
        </td>
        <td>
          <%= order.utm_source %>
        </td>
        <td>
          <%= order.tar %>
        </td>
        <td>
          <%= order.ref %>
        </td>
        <td class="align-right"><%= order.display_total.to_html %></td>
        <td class='actions align-center' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <% if can? :manage, Spree::Order %>
      <%= render 'spree/admin/shared/no_objects_found',
                   resource: Spree::Order,
                   new_resource_url: spree.new_admin_order_path %>
    <% end %>
  </div>
<% end %>

<%= paginate @orders, theme: "solidus_admin" %>

# touched on 2025-07-09T17:42:50.721290Z
# touched on 2025-07-09T18:26:21.833683Z
# touched on 2025-07-09T20:36:13.721057Z