config/routes.rb
Rails.application.routes.draw do
mount SolidusPaypalCommercePlatform::Engine, at: '/solidus_paypal_commerce_platform'
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  authenticated :spree_user, ->(u) { u&.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount Spree::Core::Engine, at: '/'
  get '/export', to: 'spree/admin/products#export'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/export_interested_chapters', to: 'spree/admin/interested_chapters#export'
  get '/export_ffa_chapter_enrollments', to: 'spree/admin/ffa_chapter_enrollments#export'
  get '/export_ffa_fundraiser', to: 'spree/admin/ffa_fundraiser_calculations#export'
  post '/ebay_webhook', to: 'ebay_webhook#get_data'
  #get '/ebay_token', to: 'ebay_webhook#token_callback'

  resource :news_letter, only: [:create], defaults: { format: 'js' }

  Spree::Core::Engine.routes.draw do
    resources :stock_updates, only: [:new, :create]
    devise_scope :spree_user do
      post 'user_registration', to: 'user_sessions#user_registration'
      post 'forget_password', to: 'user_sessions#forget_password'
    end

    devise_for :spree_user,class_name: Spree.user_class, only: [:omniauth_callbacks], controllers: { omniauth_callbacks: 'spree/user_omniauth_callbacks' }

    namespace :admin do
      resources :product_questions, only: [:index, :destroy, :edit, :update] do
        member do
          get :publish
        end
      end
      resources :cta_images
      resources :contacts, only: [:index, :show]
      resources :labels
      resources :featured_products, only: [:index] do
        collection do
          post :update_positions
        end
      end

      resources :deals_products, only: [:index] do
        collection do
          post :update_deals_position
        end
      end
      resources :google_product_categories, only: [:index, :create]
      resources :bulk_update_product_prices, only: [:index, :create]
      resources :bulk_update_sale_prices, only: [:index, :create]
      resources :email_logs, only: [:index]
      resources :ffa_chapter_enrollments
      resources :change_logs, only: [:index]
      resources :ebay_change_logs, only: [:index]
      resources :ns_responses, only: [:index]
      resources :ffa_fundraiser_events, only: [:index, :create, :update]
      resources :help_centers do
        collection do
          post :update_positions
        end
      end
      resources :bulk_update_product_labels, only: [:index, :create]

      resources :tracking_lookups

      resources :labels_products, only: [:index] do
        collection do
          post :update_positions
        end
      end

      resources :store_credit_winners

      resources :ffa_fundraiser_calculations, only: [:index, :show]

      resources :facebook_api_logs, only: [:index] do
        collection do
          post :update_product_catalog
        end
      end

      resources :filter_types do
        collection do
          post :update_positions
          post :update_values_positions
        end
      end

      get '/products/:id/group_products', to: "products#group_products" , as: :group_products
      post '/products/:id/group_products', to: "products#add_group_products" , as: :add_group_products
      delete '/products/:id/group_products', to: "products#remove_group_product" , as: :remove_group_product
      post '/products/:id/add_on_product', to: "products#add_add_on_product" , as: :add_add_on_products
      get '/products/:id/add_on_product', to: "products#add_on_product" , as: :add_on_products
      delete '/products/:id/add_on_product', to: "products#remove_add_on_product" , as: :remove_add_on_product


      resources :home_page_reviews do
        collection do
          post :update_positions
        end
      end

      resources :cta_images do
        collection do
          post :update_positions
        end
      end

      delete '/filter_values/:id', to: "filter_values#destroy", as: :filter_value
      delete '/deals_page/:id/remove_image', to: "deals_page#remove_image" , as: :remove_image
      put '/deals_page/:id/edit_image', to: "deals_page#edit_image" , as: :edit_image
      get '/export_users_data', to: 'users#export'

      resources :deals_page
      resources :ebay_logs, only: [:index]
      resources :net_suite_logs, only: [:index]
      resources :net_suite_auth, only: [:index] do
        collection do
          get :consent_approved
        end
      end

      resources :interested_chapters, only: [:index, :edit, :update, :destroy]

      resources :products do
        member do
          get :bulk_update_variant_prices
        end
      end
    end

    resources :products do
      collection do
        get :deals
        get :gift_page
        get :product_reviews
        get :stock_update_notification
      end

      member do
        get :show_related
        get :reviews_form
        get :question_form
      end
    end

    resources :save_items, only: [:index, :create, :destroy]

    resources :product_categories, only: [:index, :show]
    resources :contacts, only: [:create, :new]
    resources :store_credit_winners, only: [:create, :new]

    resources :products, only: [] do
      resources :product_questions, only: %i[create new index update]
    end

    get '/product/id', to: 'products#quick_view', as: :quick_view
    get '/taxon_with_children', to: 'taxons#load_taxon_children', as: :load_taxon_children
    get '/update_upsell_modal', to: 'orders#update_upsell_modal'
    resources :taxon_options, only: [:index], defaults: { format: 'js' }
    resources :custom_hose_generator, only: [:index]
    delete '/cart/destroy_line_item', to: 'orders#destroy_line_item'
    get '/cart/increase_quantity', to: 'orders#increase_quantity'
    get '/cart/decrease_quantity', to: 'orders#decrease_quantity'
    get '/cart/update_line_item_quantity', to: 'orders#update_line_item_quantity'
    get '/', to: 'home#index_v2'
    get 'featured_products_cards', to: 'home#featured_products_cards'
    get 'best_seller_products_cards', to: 'home#best_seller_products_cards'
    get 'site_wide_products_cards', to: 'home#site_wide_products_cards'
    get 'recently_viewed_products_cards', to: 'home#recently_viewed_products_cards'
    get 'ffa_products_cards', to: 'ffa_home#ffa_products_cards'

    get '/faqs', to: 'pages#faq'
    get '/faqs_page', to: 'pages#faq_page'
    get '/privacy_policy', to: 'pages#privacy_policy'
    get '/mill', to: 'pages#mill'
    get '/shipping_policy', to: 'pages#shipping_policy'
    get '/about_us', to: 'pages#about_us'
    get '/freedom_wrap', to: 'pages#freedom_wrap'
    delete '/custom_hose_configuration', to: 'orders#destroy_custom_hose_from_line_items'
    delete '/remove_coupon', to: 'coupon_codes#remove_coupon'
    resources :ffa_fundraisers, path: :enroll
    patch 'update_chapter', to: 'checkout#update_chapter'
    post 'apply_shipment', to: 'checkout#apply_shipment_total'
    post 'remove_payment_source', to: 'checkout#remove_card_from_wallet'
    get '/august_event', to: 'pages#august_event'
    get '/populate_qty_modal', to: 'checkout#populate_qty_modal'
    get '/chuckwagon_dvd', to: 'pages#chuckwagon_dvd'
    get '/net_wraps', to: 'pages#net_wraps'
    get '/usa', to: 'pages#usa'
    get 'briddon_usa_flag_products_cards', to: 'pages#briddon_usa_flag_products_cards'
    get 'ariat_flag_products_cards', to: 'pages#ariat_flag_products_cards'
    get 'allied_flag_products_cards', to: 'pages#allied_flag_products_cards'
    get 'accessories_flag_products_cards', to: 'pages#accessories_flag_products_cards'
    get 'related_products_cards', to: 'products#related_products_cards'

    resources :e_signatures, only: [:new] do
      collection do
        post 'callbacks'
        get 'signature_url'
      end
    end

    resources :ffa_home, path: :ffa, only: [:index]
    resources :interested_chapters, only: [:create]
    resource :ns_products_data_sync, only: [:create]
    resource :paypal_tracking_number_sync, only: [:create]

    get '.well-known/apple-developer-merchantid-domain-association', to: 'stripe_apple_pay_verification_file#show'
  end
end

# touched on 2025-07-09T20:39:47.427166Z
# touched on 2025-07-09T21:00:56.925481Z
# touched on 2025-07-09T21:01:40.042415Z
# touched on 2025-07-09T21:22:03.104733Z

app/models/spree/cta_image.rb
class Spree::CtaImage < ApplicationRecord
  include TimeZoneVariation

  enum add_space: [ :left_side, :right_side, :top, :middle ]
  acts_as_list
  before_save -> { time_zone_variation(:start_at, :end_at) }, if: -> { self.changed? }
  before_create :validate_left_or_right_cta
  before_update :validate_left_or_right_cta

  validates :start_at, :end_at, presence: :true

  private

  def validate_left_or_right_cta
    return if self.add_space == 'top'
    cta_images = Spree::CtaImage.all.where(add_space: self.add_space).where.not(id: self.id)

    if cta_images.present?
      cta_images.each do |cta_image|
        if (self.start_at <= cta_image.end_at) && (cta_image.start_at <= self.end_at)
          raise  ActiveRecord::ActiveRecordError, "The CTA in this time frame already exist"
        end
      end
    end
  end
end

# touched on 2025-07-09T17:31:38.996279Z
# touched on 2025-07-09T18:18:48.840339Z
# touched on 2025-07-09T21:01:36.579309Z

app/controllers/spree/admin/cta_images_controller.rb
module Spree
  class Admin::CtaImagesController < Spree::Admin::BaseController
    before_action :set_cta_image, only: %w[ show edit update destroy ]
    helper Spree::BaseHelper

    def new
      @cta_image = Spree::CtaImage.new
    end

    def create
      @cta_image = Spree::CtaImage.new cta_images_params

      respond_to do |format|
        begin
          if @cta_image.save
            format.html { redirect_to admin_cta_images_url, notice: "Cta Image was successfully created." }
            format.json { render :show, status: :created, location: @cta_image }
          else
            format.html { render :new, status: :unprocessable_entity }
          end
        rescue ActiveRecord::ActiveRecordError => error
          flash[:error] = error.message
          format.html { redirect_to admin_cta_images_url }
        end
      end

    end

    def index
      @cta_images = Spree::CtaImage.all
    end

    def edit
    end

    def update_positions
      ActiveRecord::Base.transaction do
        positions = params[:positions]
        records = Spree::CtaImage.where(id: positions.keys).to_a

        positions.each do |id, index|
          records.find { |r| r.id == id.to_i }&.update!(position: index)
        end
      end

      respond_to do |format|
        format.js { head :no_content }
      end
    end

    def update
      respond_to do |format|
        begin
          if @cta_image.update(cta_images_params)
            format.html { redirect_to admin_cta_images_url, notice: "Cta_image was successfully updated." }
            format.json { render :show, status: :ok, location: @cta_iage }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @cta_image.errors, status: :unprocessable_entity }
          end
        rescue ActiveRecord::ActiveRecordError => error
          flash[:error] = error.message
          format.html { redirect_to admin_cta_images_url }
        end
      end
    end

    def destroy
      @cta_image.destroy
      respond_to do |format|
        format.html { redirect_to admin_cta_images_url, notice: "Cta_image was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    def set_cta_image
      @cta_image = Spree::CtaImage.find(params[:id])
    end

    def cta_images_params
      params.require(:cta_image).permit(:start_at, :end_at, :desktop_link, :tab_link, :mobile_link, :redirect_to, :add_space)
    end
  end
end

# touched on 2025-07-09T17:42:01.854965Z
# touched on 2025-07-09T19:41:20.908181Z
# touched on 2025-07-09T20:53:24.106117Z
# touched on 2025-07-09T20:56:58.315619Z

app/views/spree/admin/cta_images/_cta_tab.html.erb
<% if cta_images.length > 0 %>
  <table class="index sortable inline-editable-table" id="listing_products" data-hook="featured_products_table"
  data-sortable-link="<%= update_positions_admin_cta_images_url(@cta_image) %>">
    <thead>
      <tr>
        <th></th>
        <th><%= Spree::CtaImage.human_attribute_name(:desktop_link) %></th>
        <th> Image </th>
        <th><%= Spree::CtaImage.human_attribute_name(:start_at) %></th>
        <th><%= Spree::CtaImage.human_attribute_name(:end_at) %></th>

        <th> Ad Space </th>
        <th colspan="3"></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% cta_images.each do |cta_image| %>
        <tr id="<%= spree_dom_id cta_image %>">
          <td><span class="handle"> </span></td>
          <td><%= cta_image.desktop_link %></td>
          <td class="width-5"><%= image_tag cta_image.mobile_link, class: 'w-50' %></td>

          <td><%= (cta_image.start_at).in_time_zone("Central Time (US & Canada)").strftime('%d-%m-%Y %H:%M:%S %Z') %></td>
          <td><%= (cta_image.end_at).in_time_zone("Central Time (US & Canada)").strftime('%d-%m-%Y %H:%M:%S %Z') %></td>
          <td><%= cta_image.add_space %></td>
          <td><%= link_to 'Edit', edit_admin_cta_image_path(cta_image) %></td>
          <td><%= link_to 'Delete', admin_cta_image_path(cta_image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::CtaImage %>
  </div>
<% end %>

# touched on 2025-07-09T17:31:45.135006Z
# touched on 2025-07-09T19:37:49.208783Z
# touched on 2025-07-09T20:53:59.093427Z
# touched on 2025-07-09T21:22:36.522739Z

app/views/spree/admin/cta_images/_form.html.erb
<div id="start_at_field" class="field">
  <%= f.label :start_at %>
  <%= f.text_field :start_at, value: datepicker_field_value(@cta_image.start_at&.in_time_zone("Central Time (US & Canada)"), with_time: true), placeholder: "Start at", class: 'datepicker datepicker-from fullwidth', data: { :'enable-time' => true, :'default-hour' => 0 }, required: :true %>
</div>

<div id="expires_at_field" class="field">
  <%= f.label :end_at %>
  <%= f.text_field :end_at, value: datepicker_field_value(@cta_image.end_at&.in_time_zone("Central Time (US & Canada)"), with_time: true), placeholder: "End date", class: 'datepicker datepicker-to fullwidth', data: { :'enable-time' => true, :'default-hour' => 0 }, required: :true %>
</div>

<div class="row justify-content-between m-0">
  <div id="link_at_field" class="field col-5">
    <%= f.label :desktop_link %>
    <%= f.text_field :desktop_link, class: 'fullwidth' %>
  </div>

  <div id="link_at_field" class="field col-5">
    <%= f.label :tab_link %>
    <%= f.text_field :tab_link, class: 'fullwidth' %>
  </div>
</div>

<div class="row justify-content-between m-0">
  <div id="link_at_field" class="field col-5">
    <%= f.label :mobile_link %>
    <%= f.text_field :mobile_link, class: 'fullwidth' %>
  </div>

  <div id="link_at_field" class="field col-5">
    <%= f.label :redirect_to %>
    <%= f.text_field :redirect_to, class: 'fullwidth' %>
  </div>
</div>

<div data-hook="admin_product_form_promotionable">
  <%= f.field_container :add_space do %>
    <label>
      Ad Space:
    </label>

    <%= f.select :add_space, Spree::CtaImage.add_spaces.keys.map {|key| [key.humanize, key]}, {include_blank: false}, class: "custom-select" %>
  <% end %>
</div>


# touched on 2025-07-09T18:27:55.068607Z
# touched on 2025-07-09T20:37:48.516148Z
# touched on 2025-07-09T20:39:17.233391Z
# touched on 2025-07-09T21:24:10.067745Z

app/views/spree/admin/cta_images/edit.html.erb
<% admin_breadcrumb('CTA Images') %>
<h1>Edit CTA Image</h1>

<%= form_for [@admin, @cta_image], url: admin_cta_image_path do |f| %>
  <%= render partial: 'form', locals: { f: f } %>

  <div class="form-buttons filter-actions actions" data-hook="buttons">
    <%= f.submit t('spree.actions.update'), class: 'btn btn-primary' %>
    <%= link_to 'Back', admin_cta_images_path, class: 'btn btn-primary' %>
  </div>
<% end %>


# touched on 2025-07-09T17:33:28.350301Z
# touched on 2025-07-09T18:19:18.461887Z
# touched on 2025-07-09T18:24:05.680383Z
# touched on 2025-07-09T19:39:45.171793Z

app/views/spree/admin/cta_images/index.html.erb
<% admin_breadcrumb('CTA Images') %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::CtaImage) %>
    <li>
      <%= link_to 'Add new Cta Image', new_admin_cta_image_path, id: 'admin_new_cta_link', class: 'btn btn-primary' %>
    </li>
  <% end %>
<% end %>

<ul class="nav nav-tabs">
  <li class="nav-item active"><a class="nav-link text-dark active" data-toggle="tab" href="#Top">Main CTA</a></li>

  <li class="nav-item"><a class="nav-link text-dark" data-toggle="tab" href="#MiddleCta">Middle CTA</a></li>

  <li class="nav-item"><a class="nav-link text-dark" data-toggle="tab" href="#Leftside">Left CTA</a></li>

  <li class="nav-item"><a class="nav-link text-dark" data-toggle="tab" href="#Rightside">Right CTA</a></li>
</ul>

<div class="tab-content help-center">
  <div id="Top" class="tab-pane active">
    <%= render 'cta_tab', cta_images: @cta_images.top %>
  </div>

  <div id="MiddleCta" class="tab-pane">
    <%= render 'cta_tab', cta_images: @cta_images.middle %>
  </div>

  <div id="Leftside" class="tab-pane">
    <%= render 'cta_tab', cta_images: @cta_images.left_side %>
  </div>
  <div id="Rightside" class="tab-pane">
    <%= render 'cta_tab', cta_images: @cta_images.right_side %>
  </div>
</div>

# touched on 2025-07-09T17:31:54.218122Z
# touched on 2025-07-09T20:40:49.151549Z

app/views/spree/admin/cta_images/new.html.erb
<% admin_breadcrumb('CTA Images') %>

<h1>CTA Image</h1>
<%= form_for [@admin, @cta_image], url: admin_cta_images_path do |f| %>
  <%= render partial: 'form', locals: { f: f } %>

  <div class="form-buttons filter-actions actions" data-hook="buttons">
    <%= f.submit t('spree.actions.create'), class: 'btn btn-primary' %>
    <%= link_to 'Back', admin_cta_images_path, class: 'btn btn-primary' %>
  </div>
<% end %>


# touched on 2025-07-09T17:34:49.512675Z
# touched on 2025-07-09T17:37:39.570590Z
# touched on 2025-07-09T17:37:52.676159Z
# touched on 2025-07-09T17:44:04.924584Z
# touched on 2025-07-09T18:26:47.313350Z
# touched on 2025-07-09T19:41:11.947725Z
# touched on 2025-07-09T21:00:43.418407Z
# touched on 2025-07-09T21:22:00.812409Z